### ISSUE TITLE
The VM image does not have r10k installed

### ISSUE THREAD

**Issue by shekharshan** [bitfield/puppet-beginners-guide-3#2]
On the VM that I created using this project, there is not r10k installed. The fix is simple with `sudo apt-get install r10k` but thought of creating an issue.

**Comment by bitfield** [comment]
Thanks! Would you like to put in a PR to fix this?

**Comment by shekharshan** [comment]
> Thanks! Would you like to put in a PR to fix this?

Just saw your comment, I have created a PR https://github.com/bitfield/puppet-beginners-guide-3/pull/3

**Comment by bitfield** [comment]
Thanks @shekharshan. Looking more closely at this, I see that the [`vagrant_provision`](https://github.com/bitfield/puppet-beginners-guide-3/blob/master/scripts/vagrant_provision.sh) script actually installs R10K via `gem`. So I don't think we'll need this change after all—sorry if I've put you to some trouble unnecessarily.

**Comment by shekharshan** [comment]
> Thanks @shekharshan. Looking more closely at this, I see that the [`vagrant_provision`](https://github.com/bitfield/puppet-beginners-guide-3/blob/master/scripts/vagrant_provision.sh) script actually installs R10K via `gem`. So I don't think we'll need this change after all—sorry if I've put you to some trouble unnecessarily.

Interesting, for some reason I had to install it using `apt` as the command was missing. But I will close the ticket for now.
